# Generated by Django 2.2.12 on 2021-12-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checkFollowing',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.BigIntegerField(null=True),
        ),
    ]
