# Generated by Django 2.2.12 on 2021-12-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20211206_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.BigIntegerField(default=0),
        ),
    ]
