# Generated by Django 2.2.12 on 2021-12-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20211208_0921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
