# Generated by Django 2.2.12 on 2021-12-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
