# Generated by Django 2.2.12 on 2022-01-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='following',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='followers',
            new_name='userFollows',
        ),
    ]
