# Generated by Django 2.2.12 on 2022-01-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20220110_0727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
