# Generated by Django 2.2.12 on 2022-01-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
    ]
